version: "3"
services:
    web:
        image: docker.io/goksi/testing-env:latest
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        env_file:
            - ".env"
    mysql:
        image: mysql:8.0.2
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: teddy
        ports:
            - "3306:3306"
    node:
        image: node:18.14-alpine
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: /bin/sh -c "npm install && npm run dev-docker"
        ports:
            - "5173:5173"
        depends_on:
            - web
